<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LakeUI" Version="5.110.0" />
    <Compile Include="../../../release/tests/RepositoryPaths.cs" Link="RepositoryPaths.cs" />
  </ItemGroup>
</Project>
